let programsUrls = [
	"https://programas.ostelea.com/programas/grados-en-turismo/grado-en-turismo-y-ocio-mencion-en-gestion-del-ocio",
	"https://programas.ostelea.com/programas/grados-en-turismo/grado-en-turismo-y-ocio-mencion-en-direccion-de-empresas-y-destinos-turisticos",
	"https://programas.ostelea.com/programas/masters-en-turismo/master-universitario-en-gestion-internacional-del-turismo",
	"https://programas.ostelea.com/programas/masters-universitarios-en-turismo/mba-en-turismo-y-hospitality",
	"https://programas.ostelea.com/programas/masters-universitarios-en-turismo/master-in-sustainable-tourism-management-of-resources-and-destinations",
	"https://programas.ostelea.com/programas/masters-universitarios-en-turismo/master-universitario-en-organizacion-de-eventos-protocolo-y-turismo-de-negocios",
	"https://programas.ostelea.com/programas/masters-universitarios-en-turismo/master-universitario-en-direccion-hotelera",
	"https://programas.ostelea.com/programas/masters-universitarios-en-turismo/master-in-event-management-and-business-tourism",
	"https://programas.ostelea.com/node/1554",
	"https://programas.ostelea.com/programas/masters-en-turismo/master-en-organizacion-de-eventos-protocolo-y-turismo-de-negocios",
	"https://programas.ostelea.com/programas/masters-en-turismo/master-in-international-management-and-tourism",
	"https://programas.ostelea.com/programas/executive-masters-en-turismo/master-executive-en-organizacion-de-eventos-y-protocolo",
	"https://programas.ostelea.com/programas/executive-masters-en-turismo/master-executive-en-marketing-turistico-y-revenue-management-hotelero",
	"https://programas.ostelea.com/programas/masters-online-en-turismo/master-online-en-direccion-de-food-and-beverage",
	"https://programas.ostelea.com/programas/masters-online-en-turismo/online-master-in-tourism-marketing-and-revenue-management",
	"https://programas.ostelea.com/programas/masters-online-en-turismo/master-online-en-organizacion-de-eventos-protocolo-y-turismo-de-negocio",
	"https://programas.ostelea.com/programas/executive-masters-en-turismo/master-executive-en-direccion-hotelera-y-restauracion",
	"https://programas.ostelea.com/programas/executive-masters-en-turismo/master-executive-en-direccion-de-food-and-beverage",
	"https://programas.ostelea.com/programas/masters-online-en-turismo/mba-en-turismo-online",
	"https://programas.ostelea.com/programas/masters-online-en-turismo/master-online-en-marketing-turistico-y-revenue-management-hotelero",
	"https://programas.ostelea.com/programas/masters-online-en-turismo/online-master-in-hotel-management-and-hospitality",	
];
export { urls };